=== superlinked/VectorHub/docs/tools/vdb_table/vendor.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "vdb_table/schema/vendor",
  "type": "object",
  "properties": {
    "name": {"type": "string", "$comment": "About | Vendor | " },
    "links": {"allOf": [{"$ref": "#/$defs/links"}], "$comment": "About | Links | " },
    "oss": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "About | OSS | The code-base is open source and users can self-host it for free." },
    "license": {"allOf": [{"$ref": "#/$defs/stringWithSource"}], "$comment": "About | License | The license the source code is released under." },
    "dev_languages": {"allOf": [{"$ref": "#/$defs/devLanguageListWithSource"}], "$comment": "About | Dev Lang | The language the database is developed in." },
    "vector_launch_year": {"type": "integer", "$comment": "About | VSS Launch | The year of the first release for the vector search functionality." },
    "metadata_filter": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Search | Filters | Metadata filtering support within vector search - allowing users to refine results based on additional contextual information and enhancing precision in search queries. Not to be confused with filters/faceting in Lucene based keyword search." },
    "hybrid_search": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Search | Hybrid Search | Built-in blending of the 2 lists (keyword & vector search results) being done natively within the DB using something like Reciprocal Rank Fusion." },
    "facets": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Search | Facets | Built-in aggregations on facets and facet cardinality calculation (similar to Lucene)." },
    "geo_search": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Search | Geo Search | Built-in geospatial index for location queries." },
    "multi_vec": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Search | Multi-Vector | Ability to create and index multiple vectors for a given document." },
    "sparse_vectors": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Search | Sparse | Bring your own sparse vectors (e.g. TF-IDF) and have them be indexed and available for retrieval in the database." },
    "bm25": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Search | BM25 | Built-in tokenization, indexing, and scoring for BM25." },
    "full_text": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Search | Full-Text | Built-in inverted index for terms, capable of boolean queries (similar to Lucene)." },
    "embeddings_text": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Models | Text Model | Ability to plug in commonly-used embedding models for text vectorization (Sentence-transformers/HuggingFace feature extraction models)" },
    "embeddings_image": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Models | Image Model | Ability to plug in image embedding models for vectorization (e.g. CLIP)." },
    "embeddings_structured": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Models | Struct Model | Ability to plug in models used to embedd structured data like user clicks and graphs." },
    "rag": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "APIs | RAG | Calls a LLM internally for a full-stack Retrieval Augmented Generation solution." },
    "recsys": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "APIs | RecSys | Built-in support for recommendation system functionality, e.g. a solution that refines the results based on behavioral data." },
    "langchain": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "APIs | LangChain | Built-in integration with the LangChain library." },
    "llamaindex": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "APIs | LlamaIndex | Built-in integration with the LlamaIndex library." },
    "managed_cloud": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Ops | Managed | A managed cloud offering is available." },
    "pricing": {"allOf": [{"$ref": "#/$defs/stringWithSource"}], "$comment": "Ops | Pricing | The pricing models very widely, so this field is unstructured and ideally points to a pricing page." },
    "in_process": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Ops | In-process | Ability to run embedded within the application process, which leads to a simpler deployment and management in situations when the whole workload fits into one machine." },
    "multi_tenancy": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Ops | Multi-Tenant | Multi-tenancy - the ability to store multiple isolated indexes within one database instance." },
    "disk_index": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Ops | Disk Index | The vector search index can be held on disk while in use, as opposed to holding it in RAM, which makes the management of large indices more affordable." },
    "ephemeral": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Ops | Ephemeral Index | Ephemeral index support without a server." },
    "sharding": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Ops | Sharding | The search index is sharded across multiple machines." },
    "doc_size": {"allOf": [{"$ref": "#/$defs/bytesWithSource"}], "$comment": "Ops | Document Size | Maximum size of a stored document." },
    "vector_dims": {"allOf": [{"$ref": "#/$defs/integerWithSource"}], "$comment": "Ops | Vector Dims | Maximum number of vector dimensions for ANN-type indexes." },
    "int8_quantization": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Ops | Int8 Quantization | Vectors can be stored and indexed in int8 quantized format in the index. Full support requires that the float versions of the vectors need not be stored in the DB at all." },
    "binary_quantization": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Ops | Binary Quantization | Vectors can be stored and indexed in binary quantized format in the index. Full support requires that the float versions of the vectors need not be stored in the DB at all." },
    "index_types": {"allOf": [{"$ref": "#/$defs/indexTypesListWithSource"}], "$comment": "Ops | Index Types | The types of vector indexes supported by the database." },
    "github_stars": {"allOf": [{"$ref": "#/$defs/statsWithSource"}], "$comment": "Stats | GitHub ⭐ | The total number of stars for the core product repository." },
    "docker_pulls": {"allOf": [{"$ref": "#/$defs/statsWithSource"}],"$comment": "Stats | Docker Pulls | The total number of pulls for the core product's docker image." },
    "pypi_downloads": {"allOf": [{"$ref": "#/$defs/statsWithSource"}], "$comment": "Stats | PyPi Downloads | The number of downloads (in last 90 days) for the core product's python package." },
    "npm_downloads": {"allOf": [{"$ref": "#/$defs/statsWithSource"}], "$comment": "Stats | NPM Downloads | The number of downloads (in last 90 days) for the core product's NPM package." },
    "crates_io_downloads": {"allOf": [{"$ref": "#/$defs/statsWithSource"}], "$comment": "Stats | Rust Crates Downloads | The number of downloads (in last 90 days) for the core product's Rust crate." }
  },
  "$defs": {
    "links": {
      "$id": "links",
      "type": "object",
      "properties": {
        "docs": {
          "type": "string"
        },
        "github": {
          "type": "string"
        },
        "website": {
          "type": "string"
        },
        "vendor_discussion": {
          "type": "string"
        },
        "poc_github": {
          "type": "string"
        },
        "slug": {
          "type": "string"
        }
      }
    },
    "featureWithSource": {
      "$id": "featureWithSource",
      "type": "object",
      "properties": {
        "support": {
          "enum": [
            "",
            "none",
            "partial",
            "full"
          ]
        },
        "source_url": {
          "type": "string"
        },
        "comment": {
          "type": "string"
        }
      }
    },
    "stringWithSource": {
      "$id": "stringWithSource",
      "type": "object",
      "properties": {
        "value": {
          "type": "string"
        },
        "source_url": {
          "type": "string"
        },
        "comment": {
          "type": "string"
        }
      }
    },
    "indexTypesListWithSource": {
      "$id": "indexTypesListWithSource",
      "type": "object",
      "properties": {
        "value": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "FLAT",
              "HNSW",
              "FAISS",
              "ANNOY",
              "IVF",
              "IVF-PQ",
              "IVF-BQ",
              "IVF-SQ",
              "FLAT-BQ",
              "HNSW-PQ",
              "HNSW-SQ",
              "HNSW-BQ",
              "DiskANN",
              "FreshDiskANN",
              "GPU Index",
              "SCANN",
              "SPANN",
              "NGT",
              "MSTG",
              "FAISS-IVF",
              "Tree-AH",
              "SVS-VAMANA",
              "Proprietary",
              "not known"
            ]
          }
        }
      }
    },
    "devLanguageListWithSource": {
      "$id": "devLanguageListWithSource",
      "type": "object",
      "properties": {
        "value": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "",
              "python",
              "c++",
              "c",
              "c#",
              "go",
              "java",
              "kotlin",
              "scala",
              "rust",
              "erlang",
              "typescript",
              "not known"
            ]
          }
        },
        "source_url": {
          "type": "string"
        },
        "comment": {
          "type": "string"
        }
      }
    },
    "integerWithSource": {
      "$id": "integerWithSource",
      "type": "object",
      "properties": {
        "value": {
          "type": "integer"
        },
        "unlimited": {
          "type": "boolean"
        },
        "source_url": {
          "type": "string"
        },
        "comment": {
          "type": "string"
        }
      }
    },
    "statsWithSource": {
      "$id": "statsWithSource",
      "type": "object",
      "properties": {
        "value": {
          "type": "integer"
        },
        "value_90_days": {
          "type": "integer"
        },
        "source_url": {
          "type": "string"
        },
        "comment": {
          "type": "string"
        }
      }
    },
    "bytesWithSource": {
      "$id": "bytesWithSource",
      "type": "object",
      "properties": {
        "bytes": {
          "type": "integer"
        },
        "unlimited": {
          "type": "boolean"
        },
        "source_url": {
          "type": "string"
        },
        "comment": {
          "type": "string"
        }
      }
    }
  }
}

=== superlinked/VectorHub/docs/tools/vdb_table/data/anariai.json
{
  "name": "Anari AI",
  "links": {
    "docs": "",
    "github": "https://github.com/Anari-AI",
    "website": "https://anari.ai/vector-acceleration-engine/",
    "vendor_discussion": "https://github.com/superlinked/VectorHub/discussions/99",
    "poc_github": "https://github.com/jovan-stojanovic",
    "slug": "anariai"
  },
  "oss": {
    "support": "none",
    "source_url": "",
    "comment": ""
  },
  "license": {
    "value": "Proprietary",
    "source_url": "",
    "comment": ""
  },
  "dev_languages": {
    "value": [
      ""
    ],
    "source_url": "",
    "comment": ""
  },
  "vector_launch_year": 2023,
  "metadata_filter": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "hybrid_search": {
    "support": "none",
    "source_url": "",
    "comment": ""
  },
  "facets": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "geo_search": {
    "support": "none",
    "source_url": "",
    "comment": ""
  },
  "multi_vec": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "sparse_vectors": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "bm25": {
    "support": "none",
    "source_url": "",
    "comment": ""
  },
  "full_text": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "embeddings_text": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "embeddings_image": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "embeddings_structured": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "rag": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "recsys": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "langchain": {
    "support": "none",
    "source_url": "",
    "comment": ""
  },
  "llamaindex": {
    "support": "none",
    "source_url": "",
    "comment": ""
  },
  "managed_cloud": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "pricing": {
    "value": "",
    "source_url": "",
    "comment": ""
  },
  "in_process": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "multi_tenancy": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "disk_index": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "ephemeral": {
    "support": "none",
    "source_url": "",
    "comment": ""
  },
  "sharding": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "doc_size": {
    "bytes": 0,
    "unlimited": true,
    "source_url": "",
    "comment": ""
  },
  "vector_dims": {
    "value": 0,
    "unlimited": false,
    "source_url": "",
    "comment": ""
  },
  "index_types": {
    "value": [
      "Proprietary"
    ],
    "source_url": "https://anari.ai/vector-acceleration-engine/",
    "comment": "uses FPGA"
  },
  "github_stars": {
    "value": 0,
    "source_url": "",
    "comment": "",
    "value_90_days": 0
  },
  "docker_pulls": {
    "value": 0,
    "source_url": "",
    "comment": "",
    "value_90_days": 0
  },
  "pypi_downloads": {
    "value": 0,
    "source_url": "",
    "comment": "",
    "value_90_days": 0
  },
  "npm_downloads": {
    "value": 2066,
    "source_url": "https://www.npmjs.com/package/epsillajs",
    "comment": "",
    "value_90_days": 463
  },
  "crates_io_downloads": {
    "value": 0,
    "source_url": "",
    "comment": "",
    "value_90_days": 0
  }
}

=== superlinked/VectorHub/docs/tools/vdb_table/data/qdrant.json
{
  "name": "Qdrant",
  "links": {
    "docs": "https://qdrant.tech/documentation/",
    "github": "https://github.com/qdrant/qdrant",
    "website": "https://qdrant.tech/",
    "vendor_discussion": "https://github.com/superlinked/VectorHub/discussions/66",
    "poc_github": "https://github.com/atarora",
    "slug": "qdrant"
  },
  "oss": {
    "support": "full",
    "source_url": "https://github.com/qdrant/qdrant",
    "comment": ""
  },
  "license": {
    "value": "Apache-2.0",
    "source_url": "",
    "comment": ""
  },
  "dev_languages": {
    "value": [
      "rust"
    ],
    "source_url": "https://github.com/qdrant/qdrant",
    "comment": ""
  },
  "vector_launch_year": 2021,
  "metadata_filter": {
    "support": "full",
    "source_url": "https://qdrant.tech/documentation/concepts/filtering/",
    "comment": ""
  },
  "hybrid_search": {
    "support": "full",
    "source_url": "https://qdrant.tech/documentation/concepts/hybrid-queries/",
    "comment": "Supports hybrid fusion searches with dense/sparse/multi vectors"
  },
  "facets": {
    "support": "full",
    "source_url": "https://qdrant.tech/documentation/concepts/payload/?q=facet#facet-counts",
    "comment": "Supports dynamically aggregate and count unique values in fields"
  },
  "geo_search": {
    "support": "full",
    "source_url": "https://qdrant.tech/documentation/concepts/filtering/#geo",
    "comment": ""
  },
  "multi_vec": {
    "support": "full",
    "source_url": "https://qdrant.tech/documentation/concepts/vectors/#multivectors",
    "comment": ""
  },
  "sparse_vectors": {
    "support": "full",
    "source_url": "https://qdrant.tech/articles/sparse-vectors",
    "comment": ""
  },
  "bm25": {
    "support": "none",
    "source_url": "https://qdrant.tech/articles/sparse-vectors",
    "comment": ""
  },
  "full_text": {
    "support": "full",
    "source_url": "https://qdrant.tech/documentation/concepts/indexing/#full-text-index",
    "comment": ""
  },
  "embeddings_text": {
    "support": "full",
    "source_url": "https://qdrant.github.io/fastembed/examples/Supported_Models/#supported-text-embedding-models",
    "comment": "via FastEmbed (Supported models: https://qdrant.github.io/fastembed/examples/Supported_Models/#supported-text-embedding-models)"
  },
  "embeddings_image": {
    "support": "full",
    "source_url": "https://qdrant.github.io/fastembed/examples/Supported_Models/#supported-image-embedding-models",
    "comment": "via FastEmbed (Supported models: https://qdrant.github.io/fastembed/examples/Supported_Models/#supported-image-embedding-models)"
  },
  "embeddings_structured": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "rag": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "recsys": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "langchain": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "llamaindex": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "managed_cloud": {
    "support": "full",
    "source_url": "https://cloud.qdrant.io/",
    "comment": ""
  },
  "pricing": {
    "value": "Qdrant Pricing (free tier available)",
    "source_url": "https://qdrant.tech/pricing/",
    "comment": ""
  },
  "in_process": {
    "support": "partial",
    "source_url": "",
    "comment": "only in Python SDK in-memory mode"
  },
  "multi_tenancy": {
    "support": "full",
    "source_url": "https://qdrant.tech/documentation/guides/multiple-partitions/",
    "comment": "via collections/metadata"
  },
  "disk_index": {
    "support": "full",
    "source_url": "https://qdrant.tech/documentation/concepts/storage/",
    "comment": "https://qdrant.tech/documentation/concepts/storage/#configuring-memmap-storage"
  },
  "ephemeral": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "sharding": {
    "support": "full",
    "source_url": "https://qdrant.tech/documentation/guides/distributed_deployment/",
    "comment": "https://qdrant.tech/documentation/guides/distributed_deployment/#user-defined-sharding"
  },
  "doc_size": {
    "bytes": 0,
    "unlimited": true,
    "source_url": "",
    "comment": ""
  },
  "vector_dims": {
    "value": 65536,
    "unlimited": false,
    "source_url": "",
    "comment": ""
  },
  "int8_quantization": {
    "support": "partial",
    "source_url": "https://qdrant.tech/articles/scalar-quantization/#scalar-quantization",
    "comment": "via Scalar Quantization of index"
  },
  "binary_quantization": {
    "support": "partial",
    "source_url": "https://qdrant.tech/documentation/guides/quantization/#binary-quantization",
    "comment": "via Binary Quantization of index"
  },
  "index_types": {
    "value": [
      "FLAT",
      "HNSW",
      "HNSW-PQ",
      "HNSW-SQ",
      "HNSW-BQ"
    ],
    "source_url": "https://qdrant.tech/documentation/concepts/indexing/",
    "comment": ""
  },
  "github_stars": {
    "value": 32547,
    "source_url": "https://github.com/qdrant/qdrant",
    "comment": "",
    "value_90_days": 0
  },
  "docker_pulls": {
    "value": 34524257,
    "source_url": "https://hub.docker.com/r/qdrant/qdrant",
    "comment": "",
    "value_90_days": 0
  },
  "pypi_downloads": {
    "value": 225886694,
    "source_url": "https://pypi.org/project/qdrant-client/",
    "comment": "",
    "value_90_days": 66358603
  },
  "npm_downloads": {
    "value": 1315891,
    "source_url": "https://www.npmjs.com/~qdrant-tech",
    "comment": "Total downloads of the REST and gRPC packages",
    "value_90_days": 551308
  },
  "crates_io_downloads": {
    "value": 2491148,
    "source_url": "https://crates.io/crates/qdrant-client",
    "comment": "",
    "value_90_days": 359185
  }
}

=== superlinked/VectorHub/docs/tools/vdb_table/data/oramasearch.json
{
  "name": "OramaSearch",
  "links": {
    "docs": "https://docs.oramasearch.com/open-source/",
    "github": "https://github.com/oramasearch/orama",
    "website": "http://oramasearch.com/",
    "vendor_discussion": "https://github.com/superlinked/VectorHub/discussions/82",
    "poc_github": "https://github.com/MicheleRiva",
    "slug": "oramasearch"
  },
  "oss": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "license": {
    "value": "Apache-2.0",
    "source_url": "",
    "comment": ""
  },
  "dev_languages": {
    "value": [
      "typescript"
    ],
    "source_url": "",
    "comment": ""
  },
  "vector_launch_year": 2022,
  "metadata_filter": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "hybrid_search": {
    "support": "none",
    "source_url": "",
    "comment": ""
  },
  "facets": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "geo_search": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "multi_vec": {
    "support": "none",
    "source_url": "",
    "comment": ""
  },
  "sparse_vectors": {
    "support": "none",
    "source_url": "",
    "comment": ""
  },
  "bm25": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "full_text": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "embeddings_text": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "embeddings_image": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "embeddings_structured": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "rag": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "recsys": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "langchain": {
    "support": "none",
    "source_url": "",
    "comment": ""
  },
  "llamaindex": {
    "support": "none",
    "source_url": "",
    "comment": ""
  },
  "managed_cloud": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "pricing": {
    "value": "free plan / $4.99 per month (pro)",
    "source_url": "https://oramasearch.com/pricing",
    "comment": ""
  },
  "in_process": {
    "support": "full",
    "source_url": "https://github.com/askorama/orama#installation",
    "comment": "Orama can work completely in-memory in your browser or server"
  },
  "multi_tenancy": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "disk_index": {
    "support": "full",
    "source_url": "https://github.com/oramasearch/orama/tree/main/packages/plugin-data-persistence",
    "comment": "Available via the official Data Persistence plugin"
  },
  "ephemeral": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "sharding": {
    "support": "",
    "source_url": "",
    "comment": "Cloud solution only"
  },
  "doc_size": {
    "bytes": 0,
    "unlimited": false,
    "source_url": "",
    "comment": ""
  },
  "vector_dims": {
    "value": 0,
    "unlimited": true,
    "source_url": "",
    "comment": ""
  },
  "github_stars": {
    "value": 10403,
    "source_url": "https://github.com/oramasearch/orama",
    "comment": "",
    "value_90_days": 0
  },
  "docker_pulls": {
    "value": 0,
    "source_url": "",
    "comment": "",
    "value_90_days": 0
  },
  "pypi_downloads": {
    "value": 0,
    "source_url": "",
    "comment": "",
    "value_90_days": 0
  },
  "npm_downloads": {
    "value": 17797520,
    "source_url": "https://www.npmjs.com/package/@orama/orama",
    "comment": "",
    "value_90_days": 8051380
  },
  "crates_io_downloads": {
    "value": 0,
    "source_url": "",
    "comment": "",
    "value_90_days": 0
  }
}

=== superlinked/VectorHub/docs/tools/vdb_table/data/apachesolr.json
{
  "name": "Apache Solr",
  "links": {
    "docs": "https://solr.apache.org/guide/solr/latest/query-guide/dense-vector-search.html",
    "github": "https://github.com/apache/solr",
    "website": "https://solr.apache.org/guide/solr/latest/query-guide/dense-vector-search.html#usage-as-re-ranking-query",
    "vendor_discussion": "https://github.com/superlinked/VectorHub/discussions/78",
    "poc_github": "https://github.com/alessandrobenedetti",
    "slug": "apachesolr"
  },
  "oss": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "license": {
    "value": "Apache-2.0",
    "source_url": "",
    "comment": ""
  },
  "dev_languages": {
    "value": [
      "java"
    ],
    "source_url": "",
    "comment": ""
  },
  "vector_launch_year": 2022,
  "metadata_filter": {
    "support": "full",
    "source_url": "https://solr.apache.org/guide/solr/latest/query-guide/dense-vector-search.html",
    "comment": "https://solr.apache.org/guide/solr/latest/query-guide/dense-vector-search.html#usage-with-filter-queries"
  },
  "hybrid_search": {
    "support": "full",
    "source_url": "https://sease.io/2023/10/apache-lucene-solr-ai-roadmap-do-you-want-to-make-it-happen.html",
    "comment": "https://sease.io/2023/10/apache-lucene-solr-ai-roadmap-do-you-want-to-make-it-happen.html linear combination implemented"
  },
  "facets": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "geo_search": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "multi_vec": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "sparse_vectors": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "bm25": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "full_text": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "embeddings_text": {
    "support": "none",
    "source_url": "",
    "comment": ""
  },
  "embeddings_image": {
    "support": "none",
    "source_url": "",
    "comment": ""
  },
  "embeddings_structured": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "rag": {
    "support": "none",
    "source_url": "",
    "comment": ""
  },
  "recsys": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "langchain": {
    "support": "",
    "source_url": "https://pypi.org/project/eurelis-langchain-solr-vectorstore/",
    "comment": "https://pypi.org/project/eurelis-langchain-solr-vectorstore/"
  },
  "llamaindex": {
    "support": "none",
    "source_url": "",
    "comment": ""
  },
  "managed_cloud": {
    "support": "full",
    "source_url": "https://www.searchstax.com/lp/managed-solr-search",
    "comment": "via https://www.searchstax.com/lp/managed-solr-search and https://bonsai.io"
  },
  "pricing": {
    "value": "",
    "source_url": "",
    "comment": ""
  },
  "in_process": {
    "support": "partial",
    "source_url": "https://solr.apache.org/docs/9_4_0/core/org/apache/solr/client/solrj/embedded/EmbeddedSolrServer.html",
    "comment": "Available via EmbeddedSolrServer for Java apps only"
  },
  "multi_tenancy": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "disk_index": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "ephemeral": {
    "support": "none",
    "source_url": "",
    "comment": ""
  },
  "sharding": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "doc_size": {
    "bytes": 0,
    "unlimited": true,
    "source_url": "",
    "comment": ""
  },
  "vector_dims": {
    "value": 0,
    "unlimited": true,
    "source_url": "https://issues.apache.org/jira/browse/SOLR-16836",
    "comment": ""
  },
  "index_types": {
    "value": [
      "FLAT",
      "HNSW"
    ],
    "source_url": "https://solr.apache.org/guide/solr/latest/query-guide/dense-vector-search.html",
    "comment": "via Lucene"
  },
  "github_stars": {
    "value": 1631,
    "source_url": "https://github.com/apache/solr",
    "comment": "",
    "value_90_days": 0
  },
  "docker_pulls": {
    "value": 353922356,
    "source_url": "https://hub.docker.com/_/solr",
    "comment": "",
    "value_90_days": 0
  },
  "pypi_downloads": {
    "value": 17220403,
    "source_url": "https://pypi.org/project/pysolr/",
    "comment": "",
    "value_90_days": 1001610
  },
  "npm_downloads": {
    "value": 449154,
    "source_url": "https://www.npmjs.com/package/solr-client",
    "comment": "",
    "value_90_days": 82594
  },
  "crates_io_downloads": {
    "value": 2355,
    "source_url": "https://crates.io/crates/solr",
    "comment": "",
    "value_90_days": 6
  }
}
