=== superlinked/VectorHub/docs/tools/vdb_table/vendor.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "vdb_table/schema/vendor",
  "type": "object",
  "properties": {
    "name": {"type": "string", "$comment": "About | Vendor | " },
    "links": {"allOf": [{"$ref": "#/$defs/links"}], "$comment": "About | Links | " },
    "oss": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "About | OSS | The code-base is open source and users can self-host it for free." },
    "license": {"allOf": [{"$ref": "#/$defs/stringWithSource"}], "$comment": "About | License | The license the source code is released under." },
    "dev_languages": {"allOf": [{"$ref": "#/$defs/devLanguageListWithSource"}], "$comment": "About | Dev Lang | The language the database is developed in." },
    "vector_launch_year": {"type": "integer", "$comment": "About | VSS Launch | The year of the first release for the vector search functionality." },
    "metadata_filter": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Search | Filters | Metadata filtering support within vector search - allowing users to refine results based on additional contextual information and enhancing precision in search queries. Not to be confused with filters/faceting in Lucene based keyword search." },
    "hybrid_search": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Search | Hybrid Search | Built-in blending of the 2 lists (keyword & vector search results) being done natively within the DB using something like Reciprocal Rank Fusion." },
    "facets": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Search | Facets | Built-in aggregations on facets and facet cardinality calculation (similar to Lucene)." },
    "geo_search": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Search | Geo Search | Built-in geospatial index for location queries." },
    "multi_vec": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Search | Multi-Vector | Ability to create and index multiple vectors for a given document." },
    "sparse_vectors": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Search | Sparse | Bring your own sparse vectors (e.g. TF-IDF) and have them be indexed and available for retrieval in the database." },
    "bm25": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Search | BM25 | Built-in tokenization, indexing, and scoring for BM25." },
    "full_text": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Search | Full-Text | Built-in inverted index for terms, capable of boolean queries (similar to Lucene)." },
    "embeddings_text": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Models | Text Model | Ability to plug in commonly-used embedding models for text vectorization (Sentence-transformers/HuggingFace feature extraction models)" },
    "embeddings_image": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Models | Image Model | Ability to plug in image embedding models for vectorization (e.g. CLIP)." },
    "embeddings_structured": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Models | Struct Model | Ability to plug in models used to embedd structured data like user clicks and graphs." },
    "rag": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "APIs | RAG | Calls a LLM internally for a full-stack Retrieval Augmented Generation solution." },
    "recsys": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "APIs | RecSys | Built-in support for recommendation system functionality, e.g. a solution that refines the results based on behavioral data." },
    "langchain": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "APIs | LangChain | Built-in integration with the LangChain library." },
    "llamaindex": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "APIs | LlamaIndex | Built-in integration with the LlamaIndex library." },
    "managed_cloud": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Ops | Managed | A managed cloud offering is available." },
    "pricing": {"allOf": [{"$ref": "#/$defs/stringWithSource"}], "$comment": "Ops | Pricing | The pricing models very widely, so this field is unstructured and ideally points to a pricing page." },
    "in_process": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Ops | In-process | Ability to run embedded within the application process, which leads to a simpler deployment and management in situations when the whole workload fits into one machine." },
    "multi_tenancy": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Ops | Multi-Tenant | Multi-tenancy - the ability to store multiple isolated indexes within one database instance." },
    "disk_index": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Ops | Disk Index | The vector search index can be held on disk while in use, as opposed to holding it in RAM, which makes the management of large indices more affordable." },
    "ephemeral": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Ops | Ephemeral Index | Ephemeral index support without a server." },
    "sharding": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Ops | Sharding | The search index is sharded across multiple machines." },
    "doc_size": {"allOf": [{"$ref": "#/$defs/bytesWithSource"}], "$comment": "Ops | Document Size | Maximum size of a stored document." },
    "vector_dims": {"allOf": [{"$ref": "#/$defs/integerWithSource"}], "$comment": "Ops | Vector Dims | Maximum number of vector dimensions for ANN-type indexes." },
    "int8_quantization": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Ops | Int8 Quantization | Vectors can be stored and indexed in int8 quantized format in the index. Full support requires that the float versions of the vectors need not be stored in the DB at all." },
    "binary_quantization": {"allOf": [{"$ref": "#/$defs/featureWithSource"}], "$comment": "Ops | Binary Quantization | Vectors can be stored and indexed in binary quantized format in the index. Full support requires that the float versions of the vectors need not be stored in the DB at all." },
    "index_types": {"allOf": [{"$ref": "#/$defs/indexTypesListWithSource"}], "$comment": "Ops | Index Types | The types of vector indexes supported by the database." },
    "github_stars": {"allOf": [{"$ref": "#/$defs/statsWithSource"}], "$comment": "Stats | GitHub ⭐ | The total number of stars for the core product repository." },
    "docker_pulls": {"allOf": [{"$ref": "#/$defs/statsWithSource"}],"$comment": "Stats | Docker Pulls | The total number of pulls for the core product's docker image." },
    "pypi_downloads": {"allOf": [{"$ref": "#/$defs/statsWithSource"}], "$comment": "Stats | PyPi Downloads | The number of downloads (in last 90 days) for the core product's python package." },
    "npm_downloads": {"allOf": [{"$ref": "#/$defs/statsWithSource"}], "$comment": "Stats | NPM Downloads | The number of downloads (in last 90 days) for the core product's NPM package." },
    "crates_io_downloads": {"allOf": [{"$ref": "#/$defs/statsWithSource"}], "$comment": "Stats | Rust Crates Downloads | The number of downloads (in last 90 days) for the core product's Rust crate." }
  },
  "$defs": {
    "links": {
      "$id": "links",
      "type": "object",
      "properties": {
        "docs": {
          "type": "string"
        },
        "github": {
          "type": "string"
        },
        "website": {
          "type": "string"
        },
        "vendor_discussion": {
          "type": "string"
        },
        "poc_github": {
          "type": "string"
        },
        "slug": {
          "type": "string"
        }
      }
    },
    "featureWithSource": {
      "$id": "featureWithSource",
      "type": "object",
      "properties": {
        "support": {
          "enum": [
            "",
            "none",
            "partial",
            "full"
          ]
        },
        "source_url": {
          "type": "string"
        },
        "comment": {
          "type": "string"
        }
      }
    },
    "stringWithSource": {
      "$id": "stringWithSource",
      "type": "object",
      "properties": {
        "value": {
          "type": "string"
        },
        "source_url": {
          "type": "string"
        },
        "comment": {
          "type": "string"
        }
      }
    },
    "indexTypesListWithSource": {
      "$id": "indexTypesListWithSource",
      "type": "object",
      "properties": {
        "value": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "FLAT",
              "HNSW",
              "FAISS",
              "ANNOY",
              "IVF",
              "IVF-PQ",
              "IVF-BQ",
              "IVF-SQ",
              "FLAT-BQ",
              "HNSW-PQ",
              "HNSW-SQ",
              "HNSW-BQ",
              "DiskANN",
              "FreshDiskANN",
              "GPU Index",
              "SCANN",
              "SPANN",
              "NGT",
              "MSTG",
              "FAISS-IVF",
              "Tree-AH",
              "SVS-VAMANA",
              "Proprietary",
              "not known"
            ]
          }
        }
      }
    },
    "devLanguageListWithSource": {
      "$id": "devLanguageListWithSource",
      "type": "object",
      "properties": {
        "value": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "",
              "python",
              "c++",
              "c",
              "c#",
              "go",
              "java",
              "kotlin",
              "scala",
              "rust",
              "erlang",
              "typescript",
              "not known"
            ]
          }
        },
        "source_url": {
          "type": "string"
        },
        "comment": {
          "type": "string"
        }
      }
    },
    "integerWithSource": {
      "$id": "integerWithSource",
      "type": "object",
      "properties": {
        "value": {
          "type": "integer"
        },
        "unlimited": {
          "type": "boolean"
        },
        "source_url": {
          "type": "string"
        },
        "comment": {
          "type": "string"
        }
      }
    },
    "statsWithSource": {
      "$id": "statsWithSource",
      "type": "object",
      "properties": {
        "value": {
          "type": "integer"
        },
        "value_90_days": {
          "type": "integer"
        },
        "source_url": {
          "type": "string"
        },
        "comment": {
          "type": "string"
        }
      }
    },
    "bytesWithSource": {
      "$id": "bytesWithSource",
      "type": "object",
      "properties": {
        "bytes": {
          "type": "integer"
        },
        "unlimited": {
          "type": "boolean"
        },
        "source_url": {
          "type": "string"
        },
        "comment": {
          "type": "string"
        }
      }
    }
  }
}

=== superlinked/VectorHub/docs/tools/vdb_table/data/paradedb.json
{
  "name": "ParadeDB",
  "links": {
    "docs": "https://docs.paradedb.com",
    "github": "https://github.com/paradedb/paradedb",
    "website": "https://paradedb.com",
    "vendor_discussion": "https://github.com/superlinked/VectorHub/discussions/401",
    "poc_github": "https://github.com/philippemnoel",
    "slug": "paradedb"
  },
  "oss": {
    "support": "full",
    "source_url": "https://github.com/paradedb/paradedb",
    "comment": ""
  },
  "license": {
    "value": "AGPL-3.0",
    "source_url": "https://github.com/paradedb/paradedb/blob/dev/LICENSE",
    "comment": ""
  },
  "dev_languages": {
    "value": [
      "rust"
    ],
    "source_url": "https://github.com/paradedb/paradedb",
    "comment": ""
  },
  "vector_launch_year": 2023,
  "metadata_filter": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "hybrid_search": {
    "support": "full",
    "source_url": "https://docs.paradedb.com/search/hybrid/basic",
    "comment": ""
  },
  "facets": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "geo_search": {
    "support": "full",
    "source_url": "https://github.com/orgs/paradedb/discussions/1110",
    "comment": "Available via the PostGIS extension"
  },
  "multi_vec": {
    "support": "none",
    "source_url": "",
    "comment": ""
  },
  "sparse_vectors": {
    "support": "full",
    "source_url": "https://docs.paradedb.com/search/sparse/overview",
    "comment": ""
  },
  "bm25": {
    "support": "full",
    "source_url": "https://docs.paradedb.com/search/full-text/overview",
    "comment": ""
  },
  "full_text": {
    "support": "full",
    "source_url": "https://docs.paradedb.com/search/full-text/overview",
    "comment": ""
  },
  "embeddings_text": {
    "support": "none",
    "source_url": "",
    "comment": ""
  },
  "embeddings_image": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "embeddings_structured": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "rag": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "recsys": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "langchain": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "llamaindex": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "managed_cloud": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "pricing": {
    "value": "",
    "source_url": "",
    "comment": ""
  },
  "in_process": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "multi_tenancy": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "disk_index": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "ephemeral": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "sharding": {
    "support": "none",
    "source_url": "",
    "comment": "While ParadeDB does not provide this natively (yet), you can get this either from PostgreSQL functionality like \"postgres_fdw\" or from extensions. You can also choose to subdivide your index through partitioning."
  },
  "doc_size": {
    "bytes": 0,
    "unlimited": false,
    "source_url": "",
    "comment": ""
  },
  "vector_dims": {
    "value": 2000,
    "unlimited": false,
    "source_url": "https://docs.paradedb.com/search/dense/index",
    "comment": ""
  },
  "index_types": {
    "value": [
      "FLAT",
      "IVF",
      "HNSW"
    ],
    "source_url": "https://github.com/pgvector/pgvector#indexing",
    "comment": ""
  },
  "github_stars": {
    "value": 8949,
    "source_url": "https://github.com/paradedb/paradedb",
    "comment": "",
    "value_90_days": 0
  },
  "docker_pulls": {
    "value": 1599595,
    "source_url": "https://hub.docker.com/r/paradedb/paradedb",
    "comment": "",
    "value_90_days": 0
  },
  "pypi_downloads": {
    "value": 0,
    "source_url": "",
    "comment": "",
    "value_90_days": 0
  },
  "npm_downloads": {
    "value": 0,
    "source_url": "",
    "comment": "",
    "value_90_days": 0
  },
  "crates_io_downloads": {
    "value": 0,
    "source_url": "",
    "comment": "",
    "value_90_days": 0
  }
}

=== superlinked/VectorHub/docs/tools/vdb_table/data/apachedoris.json
{
  "name": "Apache Doris",
  "links": {
    "docs": "https://doris.apache.org/docs/dev/ai/vector-search/",
    "github": "https://github.com/apache/doris",
    "website": "https://doris.apache.org/",
    "vendor_discussion": "https://github.com/superlinked/VectorHub/discussions/575",
    "poc_github": "https://github.com/zhiqiang-hhhh",
    "slug": "Fastest Search & Analytics in One Unified System"
  },
  "oss": {
    "support": "full",
    "source_url": "https://doris.apache.org/docs/dev/compute-storage-decoupled/overview/",
    "comment": ""
  },
  "license": {
    "value": "Apache 2.0",
    "source_url": "",
    "comment": ""
  },
  "dev_languages": {
    "value": [
      "java",
      "c++"
    ],
    "source_url": "https://github.com/apache/doris",
    "comment": ""
  },
  "vector_launch_year": 2025,
  "metadata_filter": {
    "support": "full",
    "source_url": "https://doris.apache.org/docs/dev/ai/text-search/overview/",
    "comment": ""
  },
  "hybrid_search": {
    "support": "full",
    "source_url": "https://doris.apache.org/docs/dev/ai/vector-search#ann-search-with-additional-filters",
    "comment": ""
  },
  "facets": {
    "support": "full",
    "source_url": "https://doris.apache.org/docs/dev/ai/vector-search#approximate-range-search",
    "comment": "Doris has full support for SQL. You can use standard SQL syntax to perform faceted search on vector data."
  },
  "geo_search": {
    "support": "full",
    "source_url": "https://doris.apache.org/docs/dev/sql-manual/basic-element/sql-data-types/semi-structured/GEO",
    "comment": ""
  },
  "multi_vec": {
    "support": "full",
    "source_url": "",
    "comment": "You can create a teble with multiple vector columns to store different types of vectors."
  },
  "sparse_vectors": {
    "support": "none",
    "source_url": "",
    "comment": ""
  },
  "bm25": {
    "support": "full",
    "source_url": "https://doris.apache.org/docs/dev/ai/text-search/scoring",
    "comment": ""
  },
  "full_text": {
    "support": "full",
    "source_url": "https://doris.apache.org/docs/dev/ai/text-search/search-operators",
    "comment": ""
  },
  "embeddings_text": {
    "support": "full",
    "source_url": "https://doris.apache.org/docs/4.x/sql-manual/sql-functions/ai-functions/distance-functions/embed/",
    "comment": "You can convert text to embeddings using built-in AI functions."
  },
  "embeddings_image": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "embeddings_structured": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "rag": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "recsys": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "langchain": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "llamaindex": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "managed_cloud": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "pricing": {
    "value": "",
    "source_url": "",
    "comment": ""
  },
  "in_process": {
    "support": "none",
    "source_url": "",
    "comment": ""
  },
  "multi_tenancy": {
    "support": "full",
    "source_url": "https://doris.apache.org/blog/multi-tenant-workload-isolation-in-apache-doris/",
    "comment": ""
  },
  "disk_index": {
    "support": "full",
    "source_url": "https://doris.apache.org/docs/4.x/ai/vector-search#approximate-nearest-neighbor-search",
    "comment": "Via Faiss"
  },
  "ephemeral": {
    "support": "none",
    "source_url": "",
    "comment": ""
  },
  "sharding": {
    "support": "full",
    "source_url": "",
    "comment": "Support partitioning and sharding for tables with vector columns"
  },
  "doc_size": {
    "bytes": 0,
    "unlimited": true,
    "source_url": "",
    "comment": ""
  },
  "vector_dims": {
    "value": 0,
    "unlimited": true,
    "source_url": "",
    "comment": ""
  },
  "int8_quantization": {
    "support": "full",
    "source_url": "https://doris.apache.org/docs/4.x/ai/vector-search#vector-quantization",
    "comment": ""
  },
  "index_types": {
    "value": [
      "HNSW",
      "IVF",
      "FLAT"
    ],
    "source_url": "https://doris.apache.org/docs/4.x/ai/vector-search#approximate-nearest-neighbor-search",
    "comment": "via Faiss"
  },
  "github_stars": {
    "value": 47336,
    "source_url": "https://github.com/ClickHouse/ClickHouse",
    "comment": "",
    "value_90_days": 0
  },
  "docker_pulls": {
    "value": 0,
    "source_url": "",
    "comment": "",
    "value_90_days": 0
  },
  "pypi_downloads": {
    "value": 0,
    "source_url": "",
    "comment": "",
    "value_90_days": 0
  },
  "npm_downloads": {
    "value": 0,
    "source_url": "",
    "comment": "",
    "value_90_days": 0
  },
  "crates_io_downloads": {
    "value": 0,
    "source_url": "",
    "comment": "",
    "value_90_days": 0
  }
}

=== superlinked/VectorHub/docs/tools/vdb_table/data/turbopuffer.json
{
  "name": "Turbopuffer",
  "links": {
    "docs": "https://turbopuffer.com/docs",
    "github": "https://github.com/sirupsen",
    "website": "http://turbopuffer.com/",
    "vendor_discussion": "https://github.com/superlinked/VectorHub/discussions/92",
    "poc_github": "https://github.com/sirupsen",
    "slug": "turbopuffer"
  },
  "oss": {
    "support": "none",
    "source_url": "",
    "comment": ""
  },
  "license": {
    "value": "Proprietary",
    "source_url": "",
    "comment": ""
  },
  "dev_languages": {
    "value": [
      "rust"
    ],
    "source_url": "",
    "comment": ""
  },
  "vector_launch_year": 2023,
  "metadata_filter": {
    "support": "full",
    "source_url": "https://turbopuffer.com/docs/reference/query",
    "comment": ""
  },
  "hybrid_search": {
    "support": "partial",
    "source_url": "https://turbopuffer.com/docs/hybrid-search",
    "comment": "Fusion not supported in-DB at the moment"
  },
  "facets": {
    "support": "none",
    "source_url": "",
    "comment": ""
  },
  "geo_search": {
    "support": "none",
    "source_url": "",
    "comment": ""
  },
  "multi_vec": {
    "support": "none",
    "source_url": "",
    "comment": ""
  },
  "sparse_vectors": {
    "support": "none",
    "source_url": "",
    "comment": ""
  },
  "bm25": {
    "support": "full",
    "source_url": "https://turbopuffer.com/docs/upsert#schema",
    "comment": ""
  },
  "full_text": {
    "support": "full",
    "source_url": "https://turbopuffer.com/docs/upsert#schema",
    "comment": ""
  },
  "embeddings_text": {
    "support": "none",
    "source_url": "",
    "comment": ""
  },
  "embeddings_image": {
    "support": "none",
    "source_url": "",
    "comment": ""
  },
  "embeddings_structured": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "rag": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "recsys": {
    "support": "none",
    "source_url": "",
    "comment": ""
  },
  "langchain": {
    "support": "none",
    "source_url": "",
    "comment": ""
  },
  "llamaindex": {
    "support": "none",
    "source_url": "",
    "comment": ""
  },
  "managed_cloud": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "pricing": {
    "value": "$1/million vecs, $4/million queries",
    "source_url": "https://turbopuffer.com/",
    "comment": ""
  },
  "in_process": {
    "support": "none",
    "source_url": "",
    "comment": ""
  },
  "multi_tenancy": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "disk_index": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "ephemeral": {
    "support": "none",
    "source_url": "",
    "comment": ""
  },
  "sharding": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "doc_size": {
    "bytes": 65536,
    "unlimited": false,
    "source_url": "",
    "comment": ""
  },
  "vector_dims": {
    "value": 10752,
    "unlimited": false,
    "source_url": "https://turbopuffer.com/docs/get-started/limits",
    "comment": ""
  },
  "index_types": {
    "value": [
      "SPANN"
    ],
    "source_url": "https://turbopuffer.com/architecture#:~:text=on%20SPANN.-,SPANN,-is%20a%20centroid",
    "comment": ""
  },
  "github_stars": {
    "value": 0,
    "source_url": "",
    "comment": "",
    "value_90_days": 0
  },
  "docker_pulls": {
    "value": 0,
    "source_url": "",
    "comment": "",
    "value_90_days": 0
  },
  "pypi_downloads": {
    "value": 21562487,
    "source_url": "https://pypi.org/project/turbopuffer/",
    "comment": "",
    "value_90_days": 10035295
  },
  "npm_downloads": {
    "value": 8163442,
    "source_url": "https://www.npmjs.com/package/@turbopuffer/turbopuffer",
    "comment": "",
    "value_90_days": 4087451
  },
  "crates_io_downloads": {
    "value": 0,
    "source_url": "",
    "comment": "",
    "value_90_days": 0
  }
}

=== superlinked/VectorHub/docs/tools/vdb_table/data/pgvectorscale.json
{
  "name": "pgvectorscale",
  "links": {
    "docs": "",
    "github": "https://github.com/timescale/pgvectorscale",
    "website": "https://github.com/timescale/pgvectorscale",
    "vendor_discussion": "https://github.com/superlinked/VectorHub/discussions/554",
    "poc_github": "https://github.com/cevian",
    "slug": "pgvectorscale"
  },
  "oss": {
    "support": "full",
    "source_url": "https://github.com/timescale/pgvectorscale",
    "comment": ""
  },
  "license": {
    "value": "PostgreSQL Licence https://opensource.org/license/postgresql/",
    "source_url": "https://opensource.org/license/postgresql/",
    "comment": ""
  },
  "dev_languages": {
    "value": [
      "rust"
    ],
    "source_url": "https://github.com/timescale/pgvectorscale",
    "comment": ""
  },
  "vector_launch_year": 2023,
  "metadata_filter": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "hybrid_search": {
    "support": "full",
    "source_url": "https://www.timescale.com/blog/postgresql-hybrid-search-using-pgvector-and-cohere",
    "comment": "Hybrid search provided by combination of PostgreSQL full text search and pgvectorscale"
  },
  "facets": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "geo_search": {
    "support": "full",
    "source_url": "",
    "comment": "Postgis"
  },
  "multi_vec": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "sparse_vectors": {
    "support": "full",
    "source_url": "https://github.com/pgvector/pgvector#sparse-vectors",
    "comment": "provided by pgvector"
  },
  "bm25": {
    "support": "full",
    "source_url": "",
    "comment": "provided by pgvector"
  },
  "full_text": {
    "support": "full",
    "source_url": "https://www.postgresql.org/docs/current/textsearch.html",
    "comment": "https://www.postgresql.org/docs/current/textsearch.html via GIST"
  },
  "embeddings_text": {
    "support": "full",
    "source_url": "https://github.com/timescale/pgai",
    "comment": ""
  },
  "embeddings_image": {
    "support": "full",
    "source_url": "https://github.com/timescale/pgai",
    "comment": ""
  },
  "embeddings_structured": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "rag": {
    "support": "full",
    "source_url": "https://github.com/timescale/pgai",
    "comment": ""
  },
  "recsys": {
    "support": "",
    "source_url": "",
    "comment": ""
  },
  "langchain": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "llamaindex": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "managed_cloud": {
    "support": "full",
    "source_url": "https://www.timescale.com/cloud",
    "comment": ""
  },
  "pricing": {
    "value": "Timescale Cloud",
    "source_url": "https://www.timescale.com/pricing",
    "comment": ""
  },
  "in_process": {
    "support": "none",
    "source_url": "",
    "comment": ""
  },
  "multi_tenancy": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "disk_index": {
    "support": "full",
    "source_url": "",
    "comment": ""
  },
  "ephemeral": {
    "support": "none",
    "source_url": "",
    "comment": ""
  },
  "sharding": {
    "support": "none",
    "source_url": "",
    "comment": "While pgvectorscale does not provide this natively, you can get this either from PostgreSQL functionality like \"postgres_fdw\" or from extensions. You can also choose to subdivide your index through partitioning."
  },
  "doc_size": {
    "bytes": 0,
    "unlimited": false,
    "source_url": "",
    "comment": ""
  },
  "vector_dims": {
    "value": 16000,
    "unlimited": false,
    "source_url": "https://github.com/timescale/pgvectorscale/pull/181",
    "comment": ""
  },
  "index_types": {
    "value": [
      "DiskANN",
      "FreshDiskANN"
    ],
    "source_url": "https://www.timescale.com/blog/how-we-made-postgresql-as-fast-as-pinecone-for-vector-data",
    "comment": ""
  },
  "github_stars": {
    "value": 3034,
    "source_url": "https://github.com/timescale/pgvectorscale",
    "comment": "",
    "value_90_days": 0
  },
  "docker_pulls": {
    "value": 0,
    "source_url": "",
    "comment": "",
    "value_90_days": 0
  },
  "pypi_downloads": {
    "value": 0,
    "source_url": "",
    "comment": "",
    "value_90_days": 0
  },
  "npm_downloads": {
    "value": 0,
    "source_url": "",
    "comment": "",
    "value_90_days": 0
  },
  "crates_io_downloads": {
    "value": 0,
    "source_url": "",
    "comment": "",
    "value_90_days": 0
  }
}
